#server:
#  port: 9930
spring:
  #  profiles: peer1
  application:
    name: spring-consumer-server
  cloud:
    config:
      name: spring-consumer-server
      profile: prod
  config:
    import: optional:configserver:http://localhost:9940

  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/nb_rrmp?serverTimezone=GMT%2B8"
    username: root
    password: 456412

    #连接池配置
#    type: com.alibaba.druid.pool.DruidDataSource


eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true    #是否注册自己的信息到Eureka Server注册中心，默认true
    fetch-registry: false   #是否拉取其他服务信息，默认true
    service-url:
      #      defaultZone: http://localhost:9911/eureka    #注册到EurekaServer 地址
      defaultZone: http://${eureka.instance.hostname}:8761/eureka, http://${eureka.instance.hostname}:8762/eureka    #注册到EurekaServer 地址



