server:
  port: 9940
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka    #注册到EurekaServer 地址


spring:
  #  profiles: peer1
  application:
    name: spring-config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/dev,classpath:/config/prod


